### ISSUE TITLE
No module named 'fast_transformers.causal_product.causal_product_cpu'

### ISSUE THREAD

**Issue by anthonyfuller7** [idiap/fast-transformers#12]
Hi there,

I am having some trouble using this library. I cloned this repo (July 19th) and ran the setup file, the setup ran but now I am getting this error (the same error occurs with pip install):

```
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/builders/__init__.py", line 29, in <module>
    from .transformer_encoder_builder import TransformerEncoderBuilder
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/builders/transformer_encoder_builder.py", line 31, in <module>
    from ..attention import AttentionLayer, FullAttention, \
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/attention/__init__.py", line 13, in <module>
    from .causal_linear_attention import CausalLinearAttention
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/attention/causal_linear_attention.py", line 12, in <module>
    from fast_transformers.causal_product import causal_dot_product 
  File "/usr/local/lib/python3.6/dist-No module named 'fast_transformers.causal_product.causal_product_cpu'packages/fast_transformers/causal_product/__init__.py", line 9, in <module>
    from .causal_product_cpu import causal_dot_product as causal_dot_product_cpu, \
ModuleNotFoundError: 
```

When I comment out importing this file (above), I get an import error on the hashing files instead, so I think the issues is these CUDA files. I am using Ubuntu 18.04 and PyTorch 1.5.1 with CUDA 10.2. However using the exact same setup procedure on Google Colab, I have no issues - Colab uses PyTorch 1.5.1 but CUDA 10.1. 

Could the CUDA version difference be the issue?

Thanks :)

**Comment by angeloskath** [comment]
It doesn't seem that the CUDA version could be the issue since it complains it cannot find the `causal_product_cpu` module. This is the CPU operations for autoregressive linear attention.

Is this error caused by simply running the following example from the docs?

```python
import torch
from fast_transformers.builders import TransformerEncoderBuilder

# Build a transformer encoder
bert = TransformerEncoderBuilder.from_kwargs(
    n_layers=12,
    n_heads=12,
    query_dimensions=64,
    value_dimensions=64,
    feed_forward_dimensions=3072,
    attention_type="full", # change this to use another
                           # attention implementation
    activation="gelu"
).get()

y = bert(torch.rand(
    10,    # batch_size
    512,   # sequence length
    64*12  # features
))
```

Also, is there a copy-paste issue in the error message? Because it seems that the last trace overlaps with the exception message.

Finally, could you perhaps fetch the latest from the repository and just build it and report the files created? For instance using the following code.

```
git clone git@github.com:idiap/fast-transformers.git
cd fast-transformers
python setup.py build_ext --inplace
find fast_transformers/ | grep so$
```

Cheers,
Angelos

**Comment by anthonyfuller7** [comment]
Thanks for the reply. I launched a fresh GC instance and installed this library via your method above. I should have mentioned this issue only happens when I use cluster-based attention, linear works no problem (and I haven't tried the others). 

The example from the docs runs fine only when *not* running on CUDA. That is, this code kicks an error:

```
import torch
from fast_transformers.builders import TransformerEncoderBuilder

# Build a transformer encoder
bert = TransformerEncoderBuilder.from_kwargs(
    n_layers=12,
    n_heads=12,
    query_dimensions=64,
    value_dimensions=64,
    feed_forward_dimensions=3072,
    attention_type="improved-clustered", # change this to use another
                           # attention implementation
    activation="gelu"
).get().cuda()

y = bert(x=torch.rand(
    10,    # batch_size
    512,   # sequence length
    64*12  # features
).cuda())
```

Here is the error:

```
Traceback (most recent call last):
  File "cluster_example.py", line 19, in <module>
    64*12  # features
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/transformers.py", line 131, in forward
    x = layer(x, attn_mask=attn_mask, length_mask=length_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/transformers.py", line 77, in forward
    key_lengths=length_mask
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/attention/attention_layer.py", line 98, in forward
    key_lengths
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/attention/improved_clustered_attention.py", line 196, in forward
    clusters, counts = self._create_query_groups(queries, query_lengths)
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/attention/improved_clustered_attention.py", line 107, in _create_query_groups
    hashes = compute_hashes(Q.view(N*H*L, E), planes).view(N, H, L)
  File "/usr/local/lib/python3.6/dist-packages/fast_transformers/hashing/__init__.py", line 29, in compute_hashes
    compute_hashes_cuda(X, A, H)
NameError: name 'compute_hashes_cuda' is not defined
```

And I double checked the hashing folder, and it does indeed contain all files:

```
__init__.py  __pycache__  hash_cpu.cpp  hash_cpu.cpython-36m-x86_64-linux-gnu.so  hash_cuda.cu
```

There were also warnings while building the library (via python setup.py build_ext --inplace):

```
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from fast_transformers/hashing/hash_cpu.cpp:9:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:392:54: note: declared here
   GenericPackedTensorAccessor<T,N,PtrTraits,index_t> packed_accessor() const & {
                                                      ^~~~~~~~~~~~~~~
fast_transformers/hashing/hash_cpu.cpp:49:49: warning: ‘at::GenericPackedTensorAccessor<T, N, PtrTraits, index_t> at::Tensor::packed_accessor() const & [with T = long int; long unsigned int N = 1; PtrTraits = at::DefaultPtrTraits; index_t = long int]’ is deprecated: packed_accessor is deprecated, use packed_accessor32 or packed_accessor64 instead [-Wdeprecated-declarations]
     int64_t *h = &H.packed_accessor<int64_t, 1>()[0];
                                                 ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from fast_transformers/hashing/hash_cpu.cpp:9:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:392:54: note: declared here
   GenericPackedTensorAccessor<T,N,PtrTraits,index_t> packed_accessor() const & {
```

That is just one of the install warnings, they all looked like this though. I know nothing about CUDA, but I'll see if I can solve this myself.

**Comment by angeloskath** [comment]
Ok, that is quite a different error than before. I can see that the CUDA extension is not built. This means that the machine which compiled the package lacks a CUDA compiler or a CUDA capable pytorch.

If you look into the [setup.py code](https://github.com/idiap/fast-transformers/blob/1061f2ffa09c6d74aa252389e47f76ae827b1064/setup.py#L99) it checks if a CUDA compiler is available and only then compiles the CUDA extensions. Your error has nothing to do with the clustered attention it would fail similarly with causal-linear or any other implementation which requires custom kernels.

**Comment by anthonyfuller7** [comment]
Here is the full output after running build:

```
                 from fast_transformers/causal_product/causal_product_cpu.cpp:7:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
   T * data() const {
       ^~~~
fast_transformers/causal_product/causal_product_cpu.cpp: In function ‘void causal_dot_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at
::Tensor, at::Tensor)’:
fast_transformers/causal_product/causal_product_cpu.cpp:162:41: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is de
precated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
             float *kvp = kv.data<float>();
                                         ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:11:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from fast_transformers/causal_product/causal_product_cpu.cpp:7:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:341:7: note: declared here
   T * data() const {
       ^~~~
creating build/lib.linux-x86_64-3.6/fast_transformers/causal_product
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack
-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/fast_transformers/causal_product/causal_produc
t_cpu.o -L/usr/local/lib/python3.6/dist-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.6/fast_transformers/causal_pr
oduct/causal_product_cpu.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/fast_transformers/hashing/hash_cpu.cpython-36m-x86_64-linux-gnu.so -> fast_transformers/hashing
copying build/lib.linux-x86_64-3.6/fast_transformers/aggregate/aggregate_cpu.cpython-36m-x86_64-linux-gnu.so -> fast_transformers/aggregate
copying build/lib.linux-x86_64-3.6/fast_transformers/clustering/hamming/cluster_cpu.cpython-36m-x86_64-linux-gnu.so -> fast_transformers/clustering/hamming
copying build/lib.linux-x86_64-3.6/fast_transformers/sparse_product/sparse_product_cpu.cpython-36m-x86_64-linux-gnu.so -> fast_transformers/sparse_product
copying build/lib.linux-x86_64-3.6/fast_transformers/sparse_product/clustered_sparse_product_cpu.cpython-36m-x86_64-linux-gnu.so -> fast_transformers/sparse_
product
copying build/lib.linux-x86_64-3.6/fast_transformers/causal_product/causal_product_cpu.cpython-36m-x86_64-linux-gnu.so -> fast_transformers/causal_product
```

**Comment by angeloskath** [comment]
Don't worry about the warnings, they are simply deprecation warnings for the CPU code (they shouldn't be there but they are not causing any problem).

Could you run `nvcc` in a shell? It is the CUDA compiler. If it is not accessible the kernels cannot be compiled; hence the errors. In case it is not accessible I suspect you are missing the [CUDA toolkit](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html).

**Comment by anthonyfuller7** [comment]
Yes, I am missing the CUDA toolkit. Which is odd. Sorry for the trouble. I'll try to figure this out...

Thanks again :)

**Comment by anthonyfuller7** [comment]
Final update: The issue is solved after adding CUDA to the PATH. I had installed CUDA fine, and never added it to the PATH. I had been running PyTorch and HuggingFace's transformers without issue - so I assumed my CUDA setup was not the problem. But this install *requires* CUDA to be on the PATH.

**Comment by angeloskath** [comment]
No trouble at all :smile: .

I am glad that it was easy to solve, perhaps in the future we could also provide binaries however it is a lot more trouble to provide binaries for many architectures than build then binaries on the host machine.
