### ISSUE TITLE
Quick start raise a ModuleNotFoundError

### ISSUE THREAD

**Issue by CaoYiqingT** [idiap/fast-transformers#99]
I have successfully prepared the required environment using "pip install --user pytorch-fast-transformers"

When I tried to run the quick start code, problem raised as follow:
Traceback (most recent call last):
  **File "quick_start.py", line 2, in <module>
    from fast_transformers.builders import TransformerEncoderBuilder
  File "/home/caoyq/fast-transformers-master/fast_transformers/builders/__init__.py", line 42, in <module>
    from ..attention import \
  File "/home/caoyq/fast-transformers-master/fast_transformers/attention/__init__.py", line 13, in <module>
    from .causal_linear_attention import CausalLinearAttention
  File "/home/caoyq/fast-transformers-master/fast_transformers/attention/causal_linear_attention.py", line 15, in <module>
    from ..causal_product import causal_dot_product
  File "/home/caoyq/fast-transformers-master/fast_transformers/causal_product/__init__.py", line 9, in <module>
    from .causal_product_cpu import causal_dot_product as causal_dot_product_cpu, \
ModuleNotFoundError: No module named 'fast_transformers.causal_product.causal_product_cpu'**

**Comment by lipmem** [comment]
Which torch version are you using?
For me it works with ```torch==1.8.1```

**Comment by angeloskath** [comment]
Hi,

I will close the issue due to inactivity, feel free to reopen it if needed.

Cheers,
Angelos
